name: Atualizar EPG a cada 1 hora

on:
  schedule:
    - cron: '0 * * * *'  # Executa de hora em hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Baixar EPG XML do link externo
        run: |
          curl -sSL --output guide.xml "http://minhatv.eu/xmltv.php?username=40937276&password=67063536&type=xml"

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Commit e Push do guide.xml
        run: |
          git add guide.xml
          git commit --allow-empty -m "EPG atualizado automaticamente"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
